[package]
name = "day2"
version = "0.1.0"
authors = ["Florian Vanhems <florian.vanhems@univ-lille.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
